<a href="https://colab.research.google.com/github/socome/2019.Spring.AI/blob/master/VLADNet_jwkim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import tensorflow as tf

from torch.autograd import Variable
from torchvision.models import resnet18

from tensorflow import keras
from keras.preprocessing import image

Using TensorFlow backend.


In [0]:
from google.colab import drive
import os

if os.path.exists('/content/gdrive')==False:
    drive.mount('/content/gdrive')
    print('Google Drive is mounted\n')
else:
    print('Google Drive is already mounted\n')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive
Google Drive is mounted



In [0]:
image_lists = os.listdir(os.path.join('./gdrive/My Drive/AILeader_Dataset/세종대 정문/'))
image_lists.sort()

img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/세종대 정문/',image_lists[0]), target_size=(128, 128))
img = image.img_to_array(img)
img = img.reshape((3,128,128))
List_door = np.array(img)
List_door = List_door[np.newaxis, :, :, :]

for ii, image_list in enumerate(image_lists): 
  if ii is not 0 :
    img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/세종대 정문/',image_list), target_size=(128, 128))
    x = image.img_to_array(img)
    x = x.reshape((3,128,128))
    x = x[np.newaxis, :, :, :]
    List_door = np.concatenate((List_door, x))

np.save('./gdrive/My Drive/AILeader_Dataset/세종대정문',List_door)
    
List_door.shape

In [0]:
image_lists = os.listdir(os.path.join('./gdrive/My Drive/AILeader_Dataset/어린이대공원정문/'))
image_lists.sort()

img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/어린이대공원정문/',image_lists[0]), target_size=(128, 128))
img = image.img_to_array(img)
img = img.reshape((3,128,128))
List_C_door = np.array(img)
List_C_door = List_C_door[np.newaxis, :, :, :]

for ii, image_list in enumerate(image_lists): 
  if ii is not 0 :
    img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/어린이대공원정문/',image_list), target_size=(128, 128))
    x = image.img_to_array(img)
    x = x.reshape((3,128,128))
    x = x[np.newaxis, :, :, :]
    List_C_door = np.concatenate((List_C_door, x))

np.save('./gdrive/My Drive/AILeader_Dataset/어린이대공원정문',List_C_door)
    
List_C_door.shape

In [0]:
image_lists = os.listdir(os.path.join('./gdrive/My Drive/AILeader_Dataset/대양AI센터/'))
image_lists.sort()

img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/대양AI센터/',image_lists[0]), target_size=(128, 128))
img = image.img_to_array(img)
img = img.reshape((3,128,128))
AI_center = np.array(img)
AI_center = AI_center[np.newaxis, :, :, :]

for ii, image_list in enumerate(image_lists): 
  if ii is not 0 :
    img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/대양AI센터/',image_list), target_size=(128, 128))
    x = image.img_to_array(img)
    x = x.reshape((3,128,128))
    x = x[np.newaxis, :, :, :]
    AI_center = np.concatenate((AI_center, x))

np.save('./gdrive/My Drive/AILeader_Dataset/대양AI센터',AI_center)
    
AI_center.shape

In [0]:
image_lists = os.listdir(os.path.join('./gdrive/My Drive/AILeader_Dataset/세종대 시계탑/'))
image_lists.sort()

img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/세종대 시계탑/',image_lists[0]), target_size=(128, 128))
img = image.img_to_array(img)
img = img.reshape((3,128,128))
C_Tower = np.array(img)
C_Tower = C_Tower[np.newaxis, :, :, :]

for ii, image_list in enumerate(image_lists): 
  if ii is not 0 :
    img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/세종대 시계탑/',image_list), target_size=(128, 128))
    x = image.img_to_array(img)
    x = x.reshape((3,128,128))
    x = x[np.newaxis, :, :, :]
    C_Tower = np.concatenate((C_Tower, x))

np.save('./gdrive/My Drive/AILeader_Dataset/세종대 시계탑',C_Tower)
    
C_Tower.shape

In [0]:
image_lists = os.listdir(os.path.join('./gdrive/My Drive/AILeader_Dataset/박물관/'))
image_lists.sort()

img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/박물관/',image_lists[0]), target_size=(128, 128))
img = image.img_to_array(img)
img = img.reshape((3,128,128))

Museum = np.array(img)
Museum = Museum[np.newaxis, :, :, :]

for ii, image_list in enumerate(image_lists): 
  if ii is not 0 :
    img = image.load_img(os.path.join('./gdrive/My Drive/AILeader_Dataset/박물관/',image_list), target_size=(128, 128))
    x = image.img_to_array(img)
    x = x.reshape((3,128,128))
    x = x[np.newaxis, :, :, :]
    Museum = np.concatenate((Museum, x))


np.save('./gdrive/My Drive/AILeader_Dataset/박물관',Museum)
    
Museum.shape

In [0]:
List_C_door = np.load('./gdrive/My Drive/AILeader_Dataset/어린이대공원정문.npy')
List_door = np.load('./gdrive/My Drive/AILeader_Dataset/세종대정문.npy')
AI_center = np.load('./gdrive/My Drive/AILeader_Dataset/대양AI센터.npy')
Museum = np.load('./gdrive/My Drive/AILeader_Dataset/박물관.npy')
C_Tower = np.load('./gdrive/My Drive/AILeader_Dataset/세종대 시계탑.npy')

In [0]:
class NetVLAD(nn.Module):
    """NetVLAD layer implementation"""

    def __init__(self, num_clusters=64, dim=128, alpha=100.0,
                 normalize_input=True):
        """
        Args:
            num_clusters : int
                The number of clusters
            dim : int
                Dimension of descriptors
            alpha : float
                Parameter of initialization. Larger value is harder assignment.
            normalize_input : bool
                If true, descriptor-wise L2 normalization is applied to input.
        """
        super(NetVLAD, self).__init__()
        self.num_clusters = num_clusters
        self.dim = dim
        self.alpha = alpha
        self.normalize_input = normalize_input
        self.conv = nn.Conv2d(dim, num_clusters, kernel_size=(1, 1), bias=True)
        self.centroids = nn.Parameter(torch.rand(num_clusters, dim))
        self._init_params()

    def _init_params(self):
        self.conv.weight = nn.Parameter(
            (2.0 * self.alpha * self.centroids).unsqueeze(-1).unsqueeze(-1)
        )
        self.conv.bias = nn.Parameter(
            - self.alpha * self.centroids.norm(dim=1)
        )

    def forward(self, x):
        N, C = x.shape[:2]

        if self.normalize_input:
            x = F.normalize(x, p=2, dim=1)  # across descriptor dim

        # soft-assignment
        soft_assign = self.conv(x).view(N, self.num_clusters, -1)
        soft_assign = F.softmax(soft_assign, dim=1)

        x_flatten = x.view(N, C, -1)
        
        # calculate residuals to each clusters
        residual = x_flatten.expand(self.num_clusters, -1, -1, -1).permute(1, 0, 2, 3) - \
            self.centroids.expand(x_flatten.size(-1), -1, -1).permute(1, 2, 0).unsqueeze(0)
        residual *= soft_assign.unsqueeze(2)
        vlad = residual.sum(dim=-1)

        vlad = F.normalize(vlad, p=2, dim=2)  # intra-normalization
        vlad = vlad.view(x.size(0), -1)  # flatten
        vlad = F.normalize(vlad, p=2, dim=1)  # L2 normalize

        return vlad


In [0]:
class EmbedNet(nn.Module):
    def __init__(self, base_model, net_vlad):
        super(EmbedNet, self).__init__()
        self.base_model = base_model
        self.net_vlad = net_vlad

    def forward(self, x):
        x = self.base_model(x)
        embedded_x = self.net_vlad(x)
        return embedded_x
      
class TripletNet(nn.Module):
    def __init__(self, embed_net):
        super(TripletNet, self).__init__()
        self.embed_net = embed_net

    def forward(self, a, p, n):
        embedded_a = self.embed_net(a)
        embedded_p = self.embed_net(p)
        embedded_n = self.embed_net(n)
        return embedded_a, embedded_p, embedded_n

    def feature_extract(self, x):
        return self.embed_net(x)

In [0]:
class HardTripletLoss(nn.Module):
    """Hard/Hardest Triplet Loss
    (pytorch implementation of https://omoindrot.github.io/triplet-loss)
    For each anchor, we get the hardest positive and hardest negative to form a triplet.
    """
    def __init__(self, margin=0.1, hardest=False, squared=False):
        """
        Args:
            margin: margin for triplet loss
            hardest: If true, loss is considered only hardest triplets.
            squared: If true, output is the pairwise squared euclidean distance matrix.
                If false, output is the pairwise euclidean distance matrix.
        """
        super(HardTripletLoss, self).__init__()
        self.margin = margin
        self.hardest = hardest
        self.squared = squared

    def forward(self, embeddings, labels):
        """
        Args:
            labels: labels of the batch, of size (batch_size,)
            embeddings: tensor of shape (batch_size, embed_dim)
        Returns:
            triplet_loss: scalar tensor containing the triplet loss
        """
        pairwise_dist = _pairwise_distance(embeddings, squared=self.squared)

        if self.hardest:
            # Get the hardest positive pairs
            mask_anchor_positive = _get_anchor_positive_triplet_mask(labels).float()
            valid_positive_dist = pairwise_dist * mask_anchor_positive
            hardest_positive_dist, _ = torch.max(valid_positive_dist, dim=1, keepdim=True)

            # Get the hardest negative pairs
            mask_anchor_negative = _get_anchor_negative_triplet_mask(labels).float()
            max_anchor_negative_dist, _ = torch.max(pairwise_dist, dim=1, keepdim=True)
            anchor_negative_dist = pairwise_dist + max_anchor_negative_dist * (
                    1.0 - mask_anchor_negative)
            hardest_negative_dist, _ = torch.min(anchor_negative_dist, dim=1, keepdim=True)

            # Combine biggest d(a, p) and smallest d(a, n) into final triplet loss
            triplet_loss = F.relu(hardest_positive_dist - hardest_negative_dist + 0.1)
            triplet_loss = torch.mean(triplet_loss)
        else:
            anc_pos_dist = pairwise_dist.unsqueeze(dim=2)
            anc_neg_dist = pairwise_dist.unsqueeze(dim=1)

            # Compute a 3D tensor of size (batch_size, batch_size, batch_size)
            # triplet_loss[i, j, k] will contain the triplet loss of anc=i, pos=j, neg=k
            # Uses broadcasting where the 1st argument has shape (batch_size, batch_size, 1)
            # and the 2nd (batch_size, 1, batch_size)
            loss = anc_pos_dist - anc_neg_dist + self.margin

            mask = _get_triplet_mask(labels).float()
            triplet_loss = loss * mask

            # Remove negative losses (i.e. the easy triplets)
            triplet_loss = F.relu(triplet_loss)

            # Count number of hard triplets (where triplet_loss > 0)
            hard_triplets = torch.gt(triplet_loss, 1e-16).float()
            num_hard_triplets = torch.sum(hard_triplets)

            triplet_loss = torch.sum(triplet_loss) / (num_hard_triplets + 1e-16)

        return triplet_loss


def _pairwise_distance(x, squared=False, eps=1e-16):
    # Compute the 2D matrix of distances between all the embeddings.

    cor_mat = torch.matmul(x, x.t())
    norm_mat = cor_mat.diag()
    distances = norm_mat.unsqueeze(1) - 2 * cor_mat + norm_mat.unsqueeze(0)
    distances = F.relu(distances)

    if not squared:
        mask = torch.eq(distances, 0.0).float()
        distances = distances + mask * eps
        distances = torch.sqrt(distances)
        distances = distances * (1.0 - mask)

    return distances


def _get_anchor_positive_triplet_mask(labels):
    # Return a 2D mask where mask[a, p] is True iff a and p are distinct and have same label.

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    indices_not_equal = torch.eye(labels.shape[0]).to(device).byte() ^ 1

    # Check if labels[i] == labels[j]
    labels_equal = torch.unsqueeze(labels, 0) == torch.unsqueeze(labels, 1)

    mask = indices_not_equal * labels_equal

    return mask


def _get_anchor_negative_triplet_mask(labels):
    # Return a 2D mask where mask[a, n] is True iff a and n have distinct labels.

    # Check if labels[i] != labels[k]
    labels_equal = torch.unsqueeze(labels, 0) == torch.unsqueeze(labels, 1)
    mask = labels_equal ^ 1

    return mask


def _get_triplet_mask(labels):
    """Return a 3D mask where mask[a, p, n] is True iff the triplet (a, p, n) is valid.
    A triplet (i, j, k) is valid if:
        - i, j, k are distinct
        - labels[i] == labels[j] and labels[i] != labels[k]
    """
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    # Check that i, j and k are distinct
    indices_not_same = torch.eye(labels.shape[0]).to(device).byte() ^ 1
    i_not_equal_j = torch.unsqueeze(indices_not_same, 2)
    i_not_equal_k = torch.unsqueeze(indices_not_same, 1)
    j_not_equal_k = torch.unsqueeze(indices_not_same, 0)
    distinct_indices = i_not_equal_j * i_not_equal_k * j_not_equal_k

    # Check if labels[i] == labels[j] and labels[i] != labels[k]
    label_equal = torch.eq(torch.unsqueeze(labels, 0), torch.unsqueeze(labels, 1))
    i_equal_j = torch.unsqueeze(label_equal, 2)
    i_equal_k = torch.unsqueeze(label_equal, 1)
    valid_labels = i_equal_j * (i_equal_k ^ 1)

    mask = distinct_indices * valid_labels   # Combine the two masks

    return mask

In [0]:
# Discard layers at the end of base network
encoder = resnet18(pretrained=True)
base_model = nn.Sequential(
    encoder.conv1,
    encoder.bn1,
    encoder.relu,
    encoder.maxpool,
    encoder.layer1,
    encoder.layer2,
    encoder.layer3,
    encoder.layer4,
)
dim = list(base_model.parameters())[-1].shape[0]  # last channels (512)

# Define model for embedding
net_vlad = NetVLAD(num_clusters=32, dim=dim, alpha=1.0)
model = EmbedNet(base_model, net_vlad).cuda()

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/checkpoints/resnet18-5c106cde.pth
100%|██████████| 46827520/46827520 [00:01<00:00, 28387171.78it/s]


In [0]:
# Define loss
criterion = HardTripletLoss(margin=0.1).cuda()

In [0]:
print(List_door.shape,List_C_door.shape,AI_center.shape,Museum.shape,C_Tower.shape)

(98, 3, 128, 128) (170, 3, 128, 128) (184, 3, 128, 128) (110, 3, 128, 128) (109, 3, 128, 128)


In [0]:
train_image_set = np.concatenate((List_door[:80], List_C_door[:80],AI_center[:80],Museum[:80],C_Tower[:80]))

In [0]:
train_image_set = torch.from_numpy(train_image_set)

In [0]:
train_image_set = train_image_set.cuda()

In [0]:
label_train = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
                  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
                  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                  4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4])

In [0]:
label_train = torch.from_numpy(label_train)
label_train = label_train.cuda()
label_train.shape

torch.Size([400])

In [0]:
epoch = 70
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [0]:
for ii in range(epoch):
  output_train = model(train_image_set)
  triplet_loss = criterion(output_train, label_train)
  optimizer.zero_grad()
  triplet_loss.backward(retain_graph=True)
  optimizer.step()
  
  print(ii,triplet_loss)

0 tensor(0.0984, device='cuda:0', grad_fn=<DivBackward0>)
1 tensor(0.0982, device='cuda:0', grad_fn=<DivBackward0>)
2 tensor(0.0981, device='cuda:0', grad_fn=<DivBackward0>)
3 tensor(0.0980, device='cuda:0', grad_fn=<DivBackward0>)
4 tensor(0.0978, device='cuda:0', grad_fn=<DivBackward0>)
5 tensor(0.0977, device='cuda:0', grad_fn=<DivBackward0>)
6 tensor(0.0975, device='cuda:0', grad_fn=<DivBackward0>)
7 tensor(0.0974, device='cuda:0', grad_fn=<DivBackward0>)
8 tensor(0.0972, device='cuda:0', grad_fn=<DivBackward0>)
9 tensor(0.0970, device='cuda:0', grad_fn=<DivBackward0>)
10 tensor(0.0968, device='cuda:0', grad_fn=<DivBackward0>)
11 tensor(0.0966, device='cuda:0', grad_fn=<DivBackward0>)
12 tensor(0.0964, device='cuda:0', grad_fn=<DivBackward0>)
13 tensor(0.0961, device='cuda:0', grad_fn=<DivBackward0>)
14 tensor(0.0959, device='cuda:0', grad_fn=<DivBackward0>)
15 tensor(0.0956, device='cuda:0', grad_fn=<DivBackward0>)
16 tensor(0.0953, device='cuda:0', grad_fn=<DivBackward0>)
17 tens

In [0]:
test_image_set = np.concatenate((List_door[-15:], List_C_door[-15:],AI_center[-15:],Museum[-15:],C_Tower[-15:]))
test_image_set = torch.from_numpy(test_image_set)
test_image_set = test_image_set.cuda()
print(List_door[-15:].shape,List_C_door[-15:].shape,AI_center[-15:].shape,Museum[-15:].shape,C_Tower[-15:].shape)

(15, 3, 128, 128) (15, 3, 128, 128) (15, 3, 128, 128) (15, 3, 128, 128) (15, 3, 128, 128)


In [0]:
label = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
                  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
                  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                  4,4,4,4,4,4,4,4,4,4,4,4,4,4,4])

In [0]:
# label_test = torch.from_numpy(label_test)
# label_test = label_test.cuda()
label_test.shape

torch.Size([75])

In [0]:
output_test = model(test_image_set)
output_test.shape

torch.Size([75, 16384])

In [0]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets, metrics

X = output_train.cpu().data.numpy()
Y = label_train.cpu().data.numpy()

clf = svm.SVC(gamma='scale', decision_function_shape='ovo')
clf.fit(X, Y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
X_test = output_test.cpu().data.numpy()
Y_test = label_test.cpu().data.numpy()

pred = clf.predict(X_test)

In [0]:
print(metrics.classification_report(Y_test,pred))
print(metrics.confusion_matrix(Y_test,pred))

              precision    recall  f1-score   support

           0       0.92      0.80      0.86        15
           1       0.80      0.80      0.80        15
           2       0.71      0.80      0.75        15
           3       0.58      0.73      0.65        15
           4       0.55      0.40      0.46        15

    accuracy                           0.71        75
   macro avg       0.71      0.71      0.70        75
weighted avg       0.71      0.71      0.70        75

[[12  1  0  2  0]
 [ 0 12  0  2  1]
 [ 0  1 12  0  2]
 [ 0  1  1 11  2]
 [ 1  0  4  4  6]]
